drop table if exists users cascade;
drop table if exists requests cascade;
drop table if exists items cascade;
drop table if exists comments cascade;
drop table if exists bookings cascade;

CREATE TABLE IF NOT EXISTS users(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,
email VARCHAR(512) NOT NULL,
CONSTRAINT uq_user_email UNIQUE (email));

CREATE TABLE IF NOT EXISTS requests(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
description VARCHAR(512) NOT NULL,
requestor_id BIGINT NOT NULL,
CONSTRAINT requestor_key_for_comment FOREIGN KEY(requestor_id) REFERENCES users(id));

CREATE TABLE IF NOT EXISTS items(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL, description VARCHAR(512),
is_available bool NOT NULL, owner_id BIGINT ,
request_id BIGINT,
CONSTRAINT owner_key_for_item FOREIGN KEY(owner_id) REFERENCES users(id),
CONSTRAINT request_key_for_item FOREIGN KEY(request_id) REFERENCES requests(id));

CREATE TABLE IF NOT EXISTS comments(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
text VARCHAR(512) NOT NULL, created TIMESTAMP,
item_id BIGINT NOT NULL, author_id BIGINT NOT NULL,
CONSTRAINT items_key_for_comment FOREIGN KEY(item_id) REFERENCES items(id),
CONSTRAINT users_key_for_comment FOREIGN KEY(author_id) REFERENCES users(id));

CREATE TABLE IF NOT EXISTS bookings(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
start_date TIMESTAMP,
end_date TIMESTAMP,
item_id BIGINT NOT NULL,
booker_id BIGINT NOT NULL,
status VARCHAR(125),
CONSTRAINT item_key_for_comment FOREIGN KEY(item_id) REFERENCES items(id),
CONSTRAINT booker_key_for_comment FOREIGN KEY(booker_id) REFERENCES users(id));



